---
title: "Zwischenergebnis"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(envimaR)
if (Sys.info()[["nodename"]] == "MyComputer") {
  root_folder <- "D:/plygrnd/Sen2LUI/Sen2LUI"
} else {
  root_folder <- "D:/plygrnd/Sen2LUI/Sen2LUI"
}
source(file.path(root_folder, "src/functions/000_setup.R"))
```


## Modellergebnisse

```{r, echo = FALSE}
model_files <- list.files(file.path(root_folder, "data/results/models/sat_met/"),
  pattern = glob2rx("model_202105*.rds"),
  full.names = TRUE
)
models <- lapply(model_files, function(m) {
  enviLoad(m)
})

model_performance <- lapply(models, function(m) {
  data.frame(
    model_run = m$meta$model_run,
    spacefolds = m$meta$spacefolds,
    rmse = m$dat$resample[order(m$dat$resample$Resample), "RMSE"],
    rsquared = m$dat$resample[order(m$dat$resample$Resample), "Rsquared"]#, predictor_group = meta$predictor_group
  )
})
model_performance <- do.call("rbind", model_performance)

# Add SEG_2017 (only for plot layout reasons)
model_performance <- rbind(
  model_performance,
  data.frame(
    model_run = unique(model_performance[model_performance$spacefolds == "AEG_2017", "model_run"]),
    spacefolds = "SEG_2017",
    rmse = NA,
    rsquared = NA
  )
)

spacefolds_years <- c("2017", "2018", "2019")

ggplot(
  data = model_performance[model_performance$spacefolds %in% spacefolds_years, ],
  mapping = aes(x = model_run, y = rsquared)
) +
  geom_col(position = "dodge") +
  labs(x = "Model dataset used for training", y = expression(r^2)) +
  theme_bw() +
  theme(
    text = element_text(size = 10), axis.title = element_text(size = 10), legend.text = element_text(size = 10),
    legend.position = c(0.2, 0.7), axis.text.x = element_text(angle = 90, hjust = 0.95, vjust = 0.2),
    legend.title = element_blank(), panel.background = element_blank(),
    panel.grid.major = element_blank(), panel.grid.minor = element_blank()
  ) +
  facet_wrap(~spacefolds)


ggplot(
  data = model_performance[!model_performance$spacefolds %in% spacefolds_years, ],
  mapping = aes(x = model_run, y = rsquared)
) +
  geom_col(position = "dodge") +
  labs(x = "Model dataset used for training", y = expression(r^2)) +
  theme_bw() +
  theme(
    text = element_text(size = 10), axis.title = element_text(size = 10), legend.text = element_text(size = 10),
    legend.position = c(0.2, 0.7), axis.text.x = element_text(angle = 90, hjust = 0.95, vjust = 0.2),
    legend.title = element_blank(), panel.background = element_blank(),
    panel.grid.major = element_blank(), panel.grid.minor = element_blank()
  ) +
  facet_wrap(~spacefolds)

```


## Variablen

```{r, echo = FALSE}
model_files <- list.files(file.path(root_folder, "data/results/models/sat_met/"),
  pattern = glob2rx("model_202105*.rds"),
  full.names = TRUE
)
models <- lapply(model_files, function(m) {
  enviLoad(m)
})

model_variables <- lapply(models, function(m) {
  tmp <- varImp(m$dat, scale = FALSE)$importance
  df <- data.frame(model_run = rep(m$meta$model_run, nrow(tmp)),
             spacefolds = rep(m$meta$spacefolds, nrow(tmp)),
             predictors = rownames(tmp),
             predictor_importance = tmp$Overall)
  })
model_variables <- do.call("rbind", model_variables)

predictor_importance <- aggregate(model_variables$predictor_importance, by = list(model_variables$predictors), 
                                  FUN = mean)
names(predictor_importance) <- c("Predictors", "Importance")
predictor_importance[order(predictor_importance$Importance, decreasing = TRUE), ]

```

